<Menu>:
    Label
        id: ip
        text: "Samba IP:"

        font_size: 32
        pos_hint: (0.1, 1)

    Label:
        font_size: 72
        center_x: root.width / 2
        top: root.top - 50
        text: "Home Steam Machine"

    GridLayout:
        id: gamelist

        center_x: root.center_x
        top: root.center_y

        cols: 1
        width: 800
        height: self.minimum_height
